### ISSUE TITLE
SSH Tests Severity field is wrongly populated

### ISSUE THREAD

**Issue by sashank** [d4t4king/lynis-report-converter#5]
am using lynis 2.7 version 

for SSH related tests , the severity field is wrongly populated , some text from SSH String is coming inside Severity guess they are sub options inside SSH

**Comment by d4t4king** [comment]
@sashank What output format are you using?

I just updated to lynis-2.7.1 and ran the report-converter.  I don't actually get severity for SSH tests when output to HTML.

**Comment by d4t4king** [comment]
/bump for lynis-3.0.  I'm not seeing this specific issue, but I do see other warnings/suggestions with similar issues, in the HTML output.

This is an issue with the report direct from lynis, not with this "report converter" -- at least not that I've observed.

I did submit a bug/issue with lynis, and it was summarily dismissed with the statement that some output is in the "new" format, and some in the "old" format, whatever that was, and I was welcome to submit pull requests to update the ones that needed it.  I wasn't inclined to do that at the time, but it may be worthwhile.

At any rate, I'm going to close this issue for now, since it's not really a problem with this tool, but a problem with the upstream tool.  Please feel free to re-open this issue or create a new one if you feel like the problem has returned and is actually this tool, not an artifact of lynis's output.
